/**
 * Admin Notification Service
 * 
 * Specialized service for sending notifications to admins
 * Handles risk alerts, system alerts, and critical platform events
 */

import Notification from '../models/Notification';
import User from '../models/User';
import { NotificationType, NotificationPriority, NotificationStatus } from '../types/notification';
import { getIO } from '../websocket/index';

export interface AdminNotificationOptions {
  type: NotificationType;
  title: string;
  message: string;
  priority?: NotificationPriority;
  actionRequired?: boolean;
  riskEventId?: string;
  gameType?: string;
  gameId?: string;
  data?: any;
  expiresInHours?: number;
}

class AdminNotificationService {
  /**
   * Send notification to all admin users
   */
  async sendToAllAdmins(options: AdminNotificationOptions): Promise<{ success: boolean; notificationIds?: string[]; error?: string }> {
    try {
      // Get all admin users
      const admins = await User.find({ isAdmin: true }).select('_id');
      
      if (admins.length === 0) {
        console.warn('⚠️ No admin users found to send notification');
        return { success: false, error: 'No admin users found' };
      }

      const notificationIds: string[] = [];

      // Create notification for each admin
      for (const admin of admins) {
        const notification = new Notification({
          userId: admin._id,
          type: options.type,
          title: options.title,
          message: options.message,
          priority: options.priority || NotificationPriority.NORMAL,
          status: NotificationStatus.PENDING,
          isAdminOnly: true,
          riskEventId: options.riskEventId || null,
          gameType: options.gameType || null,
          gameId: options.gameId || null,
          actionRequired: options.actionRequired || false,
          autoGenerated: true,
          data: options.data || null
        });

        if (options.expiresInHours) {
          notification.expiresAt = new Date(Date.now() + (options.expiresInHours * 60 * 60 * 1000));
        }

        await notification.save();
        notificationIds.push(notification._id.toString());
      }

      // Send real-time socket notification to admins
      const io = getIO();
      io.emit('admin_notification', {
        notificationIds,
        type: options.type,
        title: options.title,
        message: options.message,
        priority: options.priority,
        actionRequired: options.actionRequired,
        riskEventId: options.riskEventId,
        gameType: options.gameType,
        gameId: options.gameId,
        timestamp: new Date().toISOString()
      });

      console.log(`📢 Admin notification sent to ${admins.length} admins: ${options.title}`);

      return { success: true, notificationIds };

    } catch (error) {
      console.error('❌ Failed to send admin notification:', error);
      return { success: false, error: 'Failed to send notification' };
    }
  }

  /**
   * Send risk control alert to admins
   */
  async sendRiskAlert(options: {
    eventType: 'high_payout' | 'consecutive_wins' | 'anomaly_detected' | 'treasury_low' | 'payout_limit' | 'payout_blocked';
    severity: 'low' | 'medium' | 'high' | 'critical';
    gameType: string;
    gameId: string;
    riskEventId: string;
    details: any;
    actionTaken?: string;
    userId?: string;
    username?: string;
  }): Promise<{ success: boolean }> {
    try {
      // Map event type to notification type
      const typeMap: Record<string, NotificationType> = {
        'high_payout': NotificationType.RISK_HIGH_PAYOUT,
        'consecutive_wins': NotificationType.RISK_CONSECUTIVE_WINS,
        'anomaly_detected': NotificationType.RISK_ANOMALY_DETECTED,
        'treasury_low': NotificationType.RISK_TREASURY_LOW,
        'payout_limit': NotificationType.RISK_PAYOUT_LIMIT,
        'payout_blocked': NotificationType.RISK_PAYOUT_BLOCKED
      };

      // Map severity to priority
      const priorityMap: Record<string, NotificationPriority> = {
        'low': NotificationPriority.LOW,
        'medium': NotificationPriority.NORMAL,
        'high': NotificationPriority.HIGH,
        'critical': NotificationPriority.URGENT
      };

      // Generate title and message
      const title = this.generateRiskAlertTitle(options.eventType, options.severity);
      const message = this.generateRiskAlertMessage(options);

      await this.sendToAllAdmins({
        type: typeMap[options.eventType] || NotificationType.ADMIN_MESSAGE,
        title,
        message,
        priority: priorityMap[options.severity],
        actionRequired: options.severity === 'critical' || options.severity === 'high',
        riskEventId: options.riskEventId,
        gameType: options.gameType,
        gameId: options.gameId,
        data: options.details,
        expiresInHours: options.severity === 'critical' ? 48 : 24
      });

      return { success: true };

    } catch (error) {
      console.error('❌ Failed to send risk alert:', error);
      return { success: false };
    }
  }

  /**
   * Generate title for risk alert
   */
  private generateRiskAlertTitle(eventType: string, severity: string): string {
    const severityEmoji = severity === 'critical' ? '🚨' : severity === 'high' ? '⚠️' : '📊';
    
    const titles: Record<string, string> = {
      'high_payout': `${severityEmoji} High Payout Detected`,
      'consecutive_wins': `${severityEmoji} Consecutive High Wins Alert`,
      'anomaly_detected': `${severityEmoji} Game Anomaly Detected`,
      'treasury_low': `${severityEmoji} Treasury Balance Low`,
      'payout_limit': `${severityEmoji} Payout Limit Reached`,
      'payout_blocked': `${severityEmoji} Payout Blocked by Risk Control`
    };

    return titles[eventType] || `${severityEmoji} Risk Control Alert`;
  }

  /**
   * Generate message for risk alert
   */
  private generateRiskAlertMessage(options: any): string {
    const { eventType, gameType, details, actionTaken } = options;

    let message = '';

    switch (eventType) {
      case 'high_payout':
        message = `High payout detected in ${gameType} game. Amount: $${details.payout?.toFixed(2) || 'N/A'}`;
        if (details.multiplier) {
          message += `, Multiplier: ${details.multiplier}x`;
        }
        break;

      case 'consecutive_wins':
        if (details.isUserSpecific && options.username) {
          message = `User "${options.username}" has ${details.consecutiveWins || 'Multiple'} consecutive high wins in ${gameType} game. Multiplier: ${details.multiplier || 'N/A'}x. Please review user activity.`;
        } else {
          message = `${details.consecutiveWins || 'Multiple'} consecutive high wins detected in ${gameType} game. Please review game patterns.`;
        }
        break;

      case 'anomaly_detected':
        message = `Statistical anomaly detected in ${gameType} game. Anomaly score: ${(details.anomalyScore * 100).toFixed(1)}%. ${details.gamesAnalyzed || 50} games analyzed.`;
        break;

      case 'treasury_low':
        message = `Treasury balance ($${details.currentBalance?.toFixed(2) || 'N/A'}) is below minimum threshold ($${details.minRequired?.toFixed(2) || 'N/A'}). Immediate action required.`;
        break;

      case 'payout_limit':
        message = `Payout limit reached. Requested: $${details.requestedPayout?.toFixed(2) || 'N/A'}, Limit: $${details.limit?.toFixed(2) || 'N/A'}.`;
        break;

      case 'payout_blocked':
        message = `Payout blocked in ${gameType} game. Amount: $${details.requestedPayout?.toFixed(2) || 'N/A'}. Reason: ${actionTaken || 'Risk control policy'}.`;
        break;

      default:
        message = `Risk control event in ${gameType} game. ${actionTaken || 'Please review.'}`;
    }

    if (actionTaken && eventType !== 'payout_blocked') {
      message += ` Action: ${actionTaken}`;
    }

    return message;
  }

  /**
   * Send system alert to admins
   */
  async sendSystemAlert(options: {
    type: 'game_error' | 'database_error' | 'payment_issue' | 'bot_alert' | 'custom';
    title: string;
    message: string;
    severity?: 'low' | 'medium' | 'high' | 'critical';
    gameType?: string;
    gameId?: string;
    data?: any;
  }): Promise<{ success: boolean }> {
    try {
      const typeMap: Record<string, NotificationType> = {
        'game_error': NotificationType.ADMIN_GAME_ERROR,
        'database_error': NotificationType.ADMIN_DATABASE_ERROR,
        'payment_issue': NotificationType.ADMIN_PAYMENT_ISSUE,
        'bot_alert': NotificationType.ADMIN_BOT_ALERT,
        'custom': NotificationType.ADMIN_MESSAGE
      };

      const priorityMap: Record<string, NotificationPriority> = {
        'low': NotificationPriority.LOW,
        'medium': NotificationPriority.NORMAL,
        'high': NotificationPriority.HIGH,
        'critical': NotificationPriority.URGENT
      };

      await this.sendToAllAdmins({
        type: typeMap[options.type],
        title: options.title,
        message: options.message,
        priority: priorityMap[options.severity || 'medium'],
        actionRequired: options.severity === 'critical' || options.severity === 'high',
        gameType: options.gameType,
        gameId: options.gameId,
        data: options.data,
        expiresInHours: 24
      });

      return { success: true };

    } catch (error) {
      console.error('❌ Failed to send system alert:', error);
      return { success: false };
    }
  }

  /**
   * Get admin notifications
   */
  async getAdminNotifications(options: {
    limit?: number;
    skip?: number;
    priority?: string;
    type?: string;
    actionRequired?: boolean;
    unreadOnly?: boolean;
  } = {}): Promise<any[]> {
    try {
      const {
        limit = 50,
        skip = 0,
        priority,
        type,
        actionRequired,
        unreadOnly
      } = options;

      const query: any = { isAdminOnly: true };

      if (priority) {
        query.priority = priority;
      }

      if (type) {
        query.type = type;
      }

      if (actionRequired !== undefined) {
        query.actionRequired = actionRequired;
      }

      if (unreadOnly) {
        query.status = { $ne: NotificationStatus.READ };
      }

      const notifications = await Notification.find(query)
        .sort({ createdAt: -1 })
        .skip(skip)
        .limit(limit)
        .populate('riskEventId')
        .populate('userId', 'username avatar')
        .populate('sentBy', 'username')
        .lean();

      return notifications;

    } catch (error) {
      console.error('❌ Error fetching admin notifications:', error);
      return [];
    }
  }

  /**
   * Get admin notification counts
   */
  async getAdminNotificationCounts(): Promise<{
    total: number;
    unread: number;
    actionRequired: number;
    byPriority: { urgent: number; high: number; normal: number; low: number };
  }> {
    try {
      const total = await Notification.countDocuments({ isAdminOnly: true });
      const unread = await Notification.countDocuments({ 
        isAdminOnly: true, 
        status: { $ne: NotificationStatus.READ } 
      });
      const actionRequired = await Notification.countDocuments({ 
        isAdminOnly: true, 
        actionRequired: true,
        status: { $ne: NotificationStatus.READ }
      });

      const urgent = await Notification.countDocuments({ 
        isAdminOnly: true, 
        priority: NotificationPriority.URGENT,
        status: { $ne: NotificationStatus.READ }
      });
      const high = await Notification.countDocuments({ 
        isAdminOnly: true, 
        priority: NotificationPriority.HIGH,
        status: { $ne: NotificationStatus.READ }
      });
      const normal = await Notification.countDocuments({ 
        isAdminOnly: true, 
        priority: NotificationPriority.NORMAL,
        status: { $ne: NotificationStatus.READ }
      });
      const low = await Notification.countDocuments({ 
        isAdminOnly: true, 
        priority: NotificationPriority.LOW,
        status: { $ne: NotificationStatus.READ }
      });

      return {
        total,
        unread,
        actionRequired,
        byPriority: { urgent, high, normal, low }
      };

    } catch (error) {
      console.error('❌ Error getting admin notification counts:', error);
      return {
        total: 0,
        unread: 0,
        actionRequired: 0,
        byPriority: { urgent: 0, high: 0, normal: 0, low: 0 }
      };
    }
  }

  /**
   * Mark admin notification as read
   */
  async markAsRead(notificationId: string, adminUserId: string): Promise<{ success: boolean }> {
    try {
      const notification = await Notification.findById(notificationId);
      console.log(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>",notification);
      if (!notification) {
        return { success: false };
      }

      // Verify it's an admin notification
      if (!notification.isAdminOnly) {
        return { success: false };
      }

      await notification.markAsRead();

      return { success: true };

    } catch (error) {
      console.error('❌ Error marking notification as read:', error);
      return { success: false };
    }
  }

  /**
   * Mark all admin notifications as read for a user
   */
  async markAllAsRead(adminUserId: string): Promise<{ success: boolean; count?: number }> {
    try {
      const result = await Notification.updateMany(
        {
          userId: adminUserId,
          isAdminOnly: true,
          status: { $ne: NotificationStatus.READ }
        },
        {
          status: NotificationStatus.READ,
          readAt: new Date()
        }
      );

      return { success: true, count: result.modifiedCount };

    } catch (error) {
      console.error('❌ Error marking all notifications as read:', error);
      return { success: false };
    }
  }

  /**
   * Delete admin notification
   */
  async deleteNotification(notificationId: string): Promise<{ success: boolean }> {
    try {
      await Notification.findByIdAndDelete(notificationId);
      return { success: true };
    } catch (error) {
      console.error('❌ Error deleting notification:', error);
      return { success: false };
    }
  }
}

const adminNotificationService = new AdminNotificationService();

export default adminNotificationService;

