export interface INotification {
  _id?: string;
  userId?: string; // If null, it's a system-wide notification
  sentBy?: string; // Admin user who sent the notification
  type: NotificationType;
  title: string;
  message: string;
  data?: any; // Additional data for the notification
  priority: NotificationPriority;
  status: NotificationStatus;
  readAt?: Date;
  expiresAt?: Date;
  
  // Admin-specific fields
  isAdminOnly?: boolean; // Only visible to admins
  riskEventId?: string; // Link to risk event if this is a risk alert
  gameType?: string; // Game related to the notification
  gameId?: string; // Specific game ID
  actionRequired?: boolean; // Requires admin action
  autoGenerated?: boolean; // System-generated vs manual
  
  createdAt: Date;
  updatedAt: Date;
}

export enum NotificationType {
  // Welcome & Account
  WELCOME = 'welcome',
  ACCOUNT_VERIFIED = 'account_verified',
  PASSWORD_UPDATED = 'password_updated',
  ACCOUNT_FROZEN = 'account_frozen',
  ACCOUNT_UNFROZEN = 'account_unfrozen',
  
  // Financial
  DEPOSIT_SUCCESS = 'deposit_success',
  DEPOSIT_FAILED = 'deposit_failed',
  WITHDRAWAL_SUCCESS = 'withdrawal_success',
  WITHDRAWAL_FAILED = 'withdrawal_failed',
  WITHDRAWAL_PENDING = 'withdrawal_pending',
  
  // Game & Achievement
  LEVEL_UP = 'level_up',
  ACHIEVEMENT_UNLOCKED = 'achievement_unlocked',
  BIG_WIN = 'big_win',
  JACKPOT_WIN = 'jackpot_win',
  
  // System
  SYSTEM_MAINTENANCE = 'system_maintenance',
  SYSTEM_UPDATE = 'system_update',
  SECURITY_ALERT = 'security_alert',
  
  // Admin
  ADMIN_MESSAGE = 'admin_message',
  GAME_DISABLED = 'game_disabled',
  GAME_ENABLED = 'game_enabled',
  
  // Admin Risk Control Alerts
  RISK_HIGH_PAYOUT = 'risk_high_payout',
  RISK_CONSECUTIVE_WINS = 'risk_consecutive_wins',
  RISK_ANOMALY_DETECTED = 'risk_anomaly_detected',
  RISK_TREASURY_LOW = 'risk_treasury_low',
  RISK_PAYOUT_LIMIT = 'risk_payout_limit',
  RISK_PAYOUT_BLOCKED = 'risk_payout_blocked',
  
  // Admin System Alerts
  ADMIN_GAME_ERROR = 'admin_game_error',
  ADMIN_DATABASE_ERROR = 'admin_database_error',
  ADMIN_PAYMENT_ISSUE = 'admin_payment_issue',
  ADMIN_BOT_ALERT = 'admin_bot_alert',
  
  // Custom
  CUSTOM = 'custom'
}

export enum NotificationPriority {
  LOW = 'low',
  NORMAL = 'normal',
  HIGH = 'high',
  URGENT = 'urgent'
}

export enum NotificationStatus {
  PENDING = 'pending',
  SENT = 'sent',
  DELIVERED = 'delivered',
  READ = 'read',
  FAILED = 'failed',
  EXPIRED = 'expired'
}

export interface NotificationTemplate {
  type: NotificationType;
  title: string;
  message: string;
  priority: NotificationPriority;
  expiresInHours?: number;
}

export interface NotificationJob {
  id: string;
  userId?: string;
  sentBy?: string; // Admin user who sent the notification
  type: NotificationType;
  title: string;
  message: string;
  data?: any;
  priority: NotificationPriority;
  expiresInHours?: number;
  scheduledFor?: Date;
  retryCount?: number;
  maxRetries?: number;
}

export interface NotificationBroadcast {
  type: NotificationType;
  title: string;
  message: string;
  data?: any;
  sentBy?: string; // Admin user who sent the notification
  priority: NotificationPriority;
  targetUsers?: string[]; // If empty, broadcast to all users
  expiresInHours?: number;
}
