import mongoose, { Schema, Document } from 'mongoose';
import { INotification, NotificationType, NotificationPriority, NotificationStatus } from '../types/notification';

export interface INotificationDocument extends Omit<INotification, '_id'>, Document {
  markAsRead(): Promise<INotificationDocument>;
  markAsDelivered(): Promise<INotificationDocument>;
  markAsFailed(): Promise<INotificationDocument>;
}

const NotificationSchema = new Schema<INotificationDocument>({
  userId: {
    type: Schema.Types.ObjectId,
    ref: 'User',
    sparse: true // Allow null values for system-wide notifications
  },
  sentBy: {
    type: Schema.Types.ObjectId,
    ref: 'User',
    sparse: true // Track which admin sent the notification
  },
  type: {
    type: String,
    enum: Object.values(NotificationType),
    required: true,
    index: true
  },
  title: {
    type: String,
    required: true,
    maxlength: 200
  },
  message: {
    type: String,
    required: true,
    maxlength: 1000
  },
  data: {
    type: Schema.Types.Mixed,
    default: null
  },
  priority: {
    type: String,
    enum: Object.values(NotificationPriority),
    default: NotificationPriority.NORMAL,
    index: true
  },
  status: {
    type: String,
    enum: Object.values(NotificationStatus),
    default: NotificationStatus.PENDING
  },
  readAt: {
    type: Date,
    default: null
  },
  expiresAt: {
    type: Date,
    index: { expireAfterSeconds: 0 } // TTL index for automatic cleanup
  },
  
  // Admin-specific fields
  isAdminOnly: {
    type: Boolean,
    default: false,
    index: true
  },
  riskEventId: {
    type: Schema.Types.ObjectId,
    ref: 'RiskEvent',
    default: null
  },
  gameType: {
    type: String,
    enum: ['crash', 'roulette', 'coinflip', 'mine', 'system', null],
    default: null,
    index: true
  },
  gameId: {
    type: String,
    default: null,
    index: true
  },
  actionRequired: {
    type: Boolean,
    default: false,
    index: true
  },
  autoGenerated: {
    type: Boolean,
    default: false
  },
  
  createdAt: {
    type: Date,
    default: Date.now,
    index: true
  },
  updatedAt: {
    type: Date,
    default: Date.now
  }
}, {
  timestamps: true,
  collection: 'notifications'
});

// Indexes for efficient querying
NotificationSchema.index({ userId: 1, status: 1, createdAt: -1 });
NotificationSchema.index({ type: 1, status: 1, createdAt: -1 });
NotificationSchema.index({ priority: 1, status: 1, createdAt: -1 });
NotificationSchema.index({ isAdminOnly: 1, status: 1, createdAt: -1 });
NotificationSchema.index({ actionRequired: 1, isAdminOnly: 1, status: 1 });
NotificationSchema.index({ riskEventId: 1 });

// Update the updatedAt field before saving
NotificationSchema.pre('save', function(next) {
  this.updatedAt = new Date();
  next();
});

// Static method to create notification with automatic expiration
NotificationSchema.statics.createWithExpiration = function(
  notificationData: Partial<INotification>,
  expiresInHours?: number
) {
  const notification = new this(notificationData);
  
  if (expiresInHours) {
    notification.expiresAt = new Date(Date.now() + (expiresInHours * 60 * 60 * 1000));
  }
  
  return notification;
};

// Instance method to mark as read
NotificationSchema.methods.markAsRead = function() {
  this.status = NotificationStatus.READ;
  this.readAt = new Date();
  return this.save();
};

// Instance method to mark as delivered
NotificationSchema.methods.markAsDelivered = function() {
  this.status = NotificationStatus.DELIVERED;
  return this.save();
};

// Instance method to mark as failed
NotificationSchema.methods.markAsFailed = function() {
  this.status = NotificationStatus.FAILED;
  return this.save();
};

export default mongoose.model<INotificationDocument>('Notification', NotificationSchema);
